name: ${PROJECTNAME}
services:

  db:
    command: --max-allowed-packet=16M --transaction-isolation=READ-COMMITTED --innodb-lock-wait-timeout=3600 --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_pw
      MARIADB_DATABASE_FILE: /run/secrets/db_name
    image: mariadb:lts
    networks:
      - "backend-tier"
    ports:
      - "${DB_HOST_PORT}:3306"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "4"
          memory: 6G
        reservations:
          memory: 512M
    stop_grace_period: 3600s
    secrets:
      - db_root_pw
      - db_user
      - db_pw
      - db_name
    volumes:
      - "./config/mariadb.cnf:/etc/mysql/conf.d/default.cnf"
      - "./volumes/db/data:/var/lib/mysql:cached"
      - "./volumes/db/init:/docker-entrypoint-initdb.d:cached"
      - "./logs/mysql:/var/log/mysql"
      - db-share:/db-share

  phpmyadmin:
    depends_on:
      - db
    environment:
      PMA_ABSOLUTE_URI: https://${BASE_DOMAIN}/_phpmyadmin/
      PMA_HOST: db
      UPLOAD_LIMIT: 512M
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: /_phpmyadmin/
      VIRTUAL_DEST: /
    image: phpmyadmin
    networks:
      - "frontend-tier"
      - "backend-tier"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 768M
        reservations:
          memory: 64M
    restart: always

  gotenberg:
    image: gotenberg/gotenberg
    command: [ 'gotenberg', '--api-timeout', '300s', '--chromium-allow-file-access-from-files', '--chromium-disable-web-security', '--chromium-ignore-certificate-errors' ]
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          memory: 64M
    restart: always
    networks:
      - "backend-tier"

  redis:
    image: redis
    networks:
      - "backend-tier"
    restart: always
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          memory: 512M

  redis-ui:
    depends_on:
      - redis
    image: patrikx3/p3x-redis-ui
    networks:
      - "frontend-tier"
      - "backend-tier"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 32M
        reservations:
          memory: 16M
    volumes:
      - "./config/p3xrs-conns.json:/settings/.p3xrs-conns.json:ro"

  mail:
    image: mailhog/mailhog
    networks:
      - "backend-tier"
    restart: always

  php:
    depends_on:
      - db
      - gotenberg
      - mail
      - phpmyadmin
      - redis-ui
    environment:
      APACHE_ALIAS: ${BASE_DOMAIN}
      APP_ENV: ${ENVIRONMENT}
      BASE_DOMAIN: ${BASE_DOMAIN}
      MAIL_DOMAIN: ${BASE_DOMAIN}
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_pw
      MARIADB_DATABASE_FILE: /run/secrets/db_name
      PHP_GC_MAX_LIFETIME: ${PHP_GC_MAX_LIFETIME:-1440}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT:-256M}
      PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING:-22527}
      PROJECTNAME: ${PROJECTNAME}
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${BASE_DOMAIN}
      VIRTUAL_PATH: /
      SELF_SIGNED_HOST: ${BASE_DOMAIN}
      XDEBUG_IP: ${XDEBUG_IP:-host.docker.internal}
      IDE_KEY: ${IDE_KEY:-PHPSTORM}
    image: fduarte42/docker-php:${PHP_VERSION}-debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - "frontend-tier"
      - "backend-tier"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "4"
          memory: 5256M
        reservations:
          memory: 256M
    secrets:
      - db_user
      - db_pw
      - db_name
    volumes:
      - "~/.ssh:/ssh"
      - "./config/crontab:/tmp/crontab"
      - "./config/htpasswd:/etc/apache2/.htpasswd:ro"
      - "./config/apache-sites:/etc/apache2/sites-enabled:ro"
      - "./config/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro"
      - "./config/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro"
      - "./htdocs:/var/www/html"
      - "./logs/apache:/var/log/apache"
      - db-share:/db-share

  logrotate:
    image: blacklabelops/logrotate:latest
    environment:
      LOGROTATE_COPIES: 12
      LOGS_DIRECTORIES: "/logs"
      LOGROTATE_INTERVAL: monthly
      LOGROTATE_COMPRESSION: compress
      LOGROTATE_STATUSFILE: /logs/logrotate.status
      LOGROTATE_DATEFORMAT: "-%Y%m%d%H%i%s"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 32M
        reservations:
          memory: 16M
    volumes:
      - "./logs:/logs"

  capistrano:
    build:
      context: "./build/capistrano"
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 32M
        reservations:
          memory: 16M
    volumes:
      - "./volumes/capistrano/Capfile:/app/Capfile:cached"
      - "./volumes/capistrano/config:/app/config:cached"
      - "./volumes/capistrano/lib:/app/lib:cached"
      - "~/.ssh:/ssh"
    networks:
      - "backend-tier"

secrets:
  db_root_pw:
    file: ./secrets/db_root_pw.txt
  db_user:
    file: ./secrets/db_user.txt
  db_pw:
    file: ./secrets/db_pw.txt
  db_name:
    file: ./secrets/db_name.txt

networks:
  frontend-tier:
    name: proxy
    external: true
  backend-tier:
    driver: bridge

volumes:
  db-share:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/db-share
