services:
  nginx:
    labels:
      com.interligent.dockerplugin.proxy: "nginx"
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.6
    networks:
      - "frontend-tier"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: any
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro,z"
      - "${HOMEBREW_PREFIX}/etc/docker-control/ingress/volumes/vhosts.d:/etc/nginx/vhost.d:ro"
      - "${HOMEBREW_PREFIX}/etc/docker-control/ingress/volumes/tls:/etc/nginx/certs:ro"
    logging:
      options:
        max-size: "100M"
        max-file: "4"

  proxy-companion:
    labels:
      com.interligent.dockerplugin.proxy: "companion"
    container_name: proxy-companion
    image: sebastienheyd/self-signed-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - "frontend-tier"
    deploy:
      restart_policy:
        condition: any
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro,z"
      - "${HOMEBREW_PREFIX}/etc/docker-control/ingress/volumes/tls:/etc/nginx/certs:rw"

networks:
  frontend-tier:
    name: proxy
